"""empty message

Revision ID: 0ea0b06f446f
Revises: 
Create Date: 2021-07-19 19:22:34.532306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea0b06f446f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Distibutor',
    sa.Column('id', app.utils.guid.GUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=0), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('id_type', sa.Enum('national_id', 'drivers_license', 'passport', 'voters_id', name='id_type'), nullable=False),
    sa.Column('id_number', sa.String(length=20), nullable=False),
    sa.Column('auth_service_id', app.utils.guid.GUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'blocked', 'first_time', name='status'), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('lead',
    sa.Column('id', app.utils.guid.GUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=0), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('id_type', sa.String(length=20), nullable=False),
    sa.Column('id_number', sa.String(length=20), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('otp_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_token', sa.String(), nullable=True),
    sa.Column('password_token_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead')
    op.drop_table('Distibutor')
    # ### end Alembic commands ###
